<?php
namespace Database\Seeders;

use App\Models\Proyek;
use Illuminate\Database\Seeder;

class ProyekSeeder extends Seeder
{
    public function run () : void
    {
        $proyek = [ "PROYEK PEMBANGUNAN BENDUNGAN KEUREUTO ACEH", "PROYEK IRIGASI D.I. LEMATANG KOTA PAGAR ALAM PHASE II PAKET 1", "PROYEK PEKERJAAN RANCANG BANGUN RUMAH SUSUN STASIUN TANJUNG BARAT JAKARTA TIMUR", "PROYEK HUNIAN TETAP PASCA BENCANA GEMPA CIANJUR TAHAP 3", "PROYEK PEMBANGUNAN BENDUNGAN BENER PAKET 1 (MYC)", "PROYEK PEMBANGUNAN BENDUNGAN BENER PAKET 4 (MYC)", "PT PARAHITA DANAPATI (BENER PAKET 1)", "PT RINDU IDOLA SEMESTA (BENER PAKET 4)", "PROYEK PEMBANGUNAN BENDUNGAN JRAGUNG PAKET III", "PROYEK PEMBANGUNAN SARANA PENGENDALIAN BANJIR SUNGAI BOGOWONTO", "PROYEK PEMBANGUNAN JALAN TOL PROBOLINGGO - BANYUWANGI PAKET 1", "PROYEK PEMBANGUNAN BENDUNGAN SIDAN (LANJUTAN)", "PT ANANDA PRATAMA (BENDUNGAN SIDAN LANJUTAN)", "PROYEK JARINGAN IRIGASI D.I. BINTANG BANO", "PT KARSA PILAR KONSTRUKSI (PERUMAHAN KUPANG)", "PROYEK PEMBANGUNAN BENDUNGAN MBAY", "PT BUMI SEKAR INDAH (BENDUNGAN MBAY)", "PT GRI (GENANGAN CIPANAS)", "PROYEK PEMBANGUNAN RUSUN ASN 4 - IKN", "PROYEK EMBUNG KIPP - IKN", "PROYEK PEMBANGUNAN BENDUNGAN SEPAKU SEMOI", "PROYEK PEMBANGUNAN BENDUNGAN SEPAKU SEMOI (LANJUTAN)", "PROYEK PENANGANAN BANJIR SUNGAI SEPAKU - IKN", "PROYEK SPAM PAKET 1 - IKN", "PROYEK SPAM PAKET 2 - IKN", "PROYEK PENATAAN SUMBU KEBANGSAAN TAHAP 1 - IKN", "PROYEK PENATAAN SUMBU KEBANGSAAN TAHAP 2 - IKN", "PROYEK JALAN BEBAS HAMBATAN SEKSI 6B - IKN", "PROYEK PEMBANGUNAN JALAN TOL IKN SEGMEN KARANGJOANG - KKT KARIANGAU - IKN", "PROYEK JALAN KERJA KAWASAN SUB BWP 1B 1C - IKN", "PROYEK PEMBANGUNAN TEMPAT PENGOLAHAN SAMPAH TERPADU - IKN", "PROYEK PEMBANGUNAN JEMBATAN NANGA PINOH - ELLA HILIR - BTS KALTENG", "PROYEK BENDUNGAN BUDONG - BUDONG", "PROYEK PEMBANGUNAN BENDUNGAN BULANGO ULU", "PT SAMA ROKHMA INDONESIA (BULANGO ULU)", "PROYEK JARINGAN IRIGASI D.I. BALIASE", "PROYEK REHABILITASI DAN REKONSTRUKSI GEDUNG DPRD MAMUJU", "PROYEK RUMAH SAKIT UPT VERTIKAL PAPUA", "PROYEK ELEVATED KARAWANG", "POOL ALAT SUBANG", "PABRIK SUBANG", "OSP IKN", "PT BUMI GRESIK (BENDUNGAN BUDONG - BUDONG)", "PT BUMI GRESIK (BENDUNGAN MBAY)", "PT ANANDA PRATAMA (BENDUNGAN JRAGUNG)", "INSTALASI PENYEDIA AIR BERSIH (IPA - IKN)", "WING 2 PUPR IKN (GEDUNG PUPR 5 TOWER)", "RS ABDI WALUYO IKN", "BENDUNGAN MARANGKAYU", "RS DJUANSIH MAJALENGKA", "PT GODAM SOLUSI (BENDUNGAN SIDAN LANJUTAN)", "PT JATI KENCANA (BENDUNGAN JRAGUNG)", "PROYEK EMBUNG LANJUTAN KIPP - IKN", "PROYEK JALAN LINGKAR SEPAKU", "PROYEK PERUMAHAN KUPANG", "PT DINAR MULIA BARAKAH (BENER PAKET 1)", "PT TRANSSINDO HUTAMA KARYA (BENER PAKET 4)", "CV NURA SAKTI (BENER 4)", "PT BUMI KARSA (PROYEK BULANGO ULU PAKET 3)", "MODULAR TNI IKN", "PT BUMI KARSA (PROYEK PRESERVASI RUAS JALAN BILUHU BARAT)" ];

        foreach ( $proyek as $nama_proyek )
        {
            Proyek::factory ()->create ( [ 'nama_proyek' => $nama_proyek ] );
        }
    }
}

