@push('styles_3')
    <style>
        #table-data {
            font-size: 0.9em;
            white-space: nowrap;
        }

        #table-data td,
        #table-data th {
            padding: 4px 8px;
            vertical-align: middle;
        }

        #no-data-message {
            text-align: center;
            padding: 20px;
            color: #999;
            display: none;
            /* Awalnya disembunyikan */
            font-size: 1.2em;
            animation: fadeIn 0.5s ease-in-out;
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
            }

            to {
                opacity: 1;
            }
        }
    </style>
@endpush

<div class="ibox-body ms-0 ps-0 table-responsive">
    <table class="m-0 table table-bordered table-striped" id="table-data">
        <thead class="table-primary">
            <tr>
                <th class="text-center">No RKB</th>
                <th class="text-center">Proyek</th>
                <th class="text-center">Periode</th>
                <th class="text-center">Aksi</th>
            </tr>
        </thead>
        <tbody>
            {{-- Content generated by DataTable --}}
        </tbody>
    </table>

    <div id="no-data-message">No Data Found</div>
</div>

@push('scripts_3')
    <script>
    </script>
@endpush