@push('styles_3')
    <style>
        #table-data {
            font-size: 0.9em;
            white-space: nowrap;
        }

        #table-data td,
        #table-data th {
            padding: 4px 8px;
            vertical-align: middle;
        }

        #no-data-message {
            text-align: center;
            padding: 20px;
            color: #999;
            display: none;
            font-size: 1.2em;
            animation: fadeIn 0.5s ease-in-out;
        }
    </style>
@endpush

<div class="ibox-body ms-0 ps-0 table-responsive">
    <table class="m-0 table table-bordered table-striped" id="table-data">
        <thead class="table-primary">
            <tr>
                <th class="text-center">No RKB</th>
                <th class="text-center">Proyek</th>
                <th class="text-center">Periode</th>
                <th class="text-center">Status</th>
                <th class="text-center">Evaluasi</th>
            </tr>
        </thead>
        <tbody>
            {{-- Content generated by DataTable --}}
        </tbody>
    </table>
</div>

@push('scripts_3')
    <script>
        $(document).ready(function() {
            const lastPageKey = 'lastPage_evaluasi_rkb';
            const lastPage = localStorage.getItem(lastPageKey) ? parseInt(localStorage.getItem(lastPageKey)) : 0;

            $('#table-data').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                ajax: {
                    url: "{{ route('evaluasi_rkb_general.getData') }}",
                    type: "GET"
                },
                language: {
                    paginate: {
                        previous: '<i class="bi bi-caret-left"></i>',
                        next: '<i class="bi bi-caret-right"></i>'
                    }
                },
                pageLength: 10,
                lengthMenu: [
                    [10, 25, 50],
                    [10, 25, 50]
                ],
                ordering: true,
                order: [],
                displayStart: lastPage * 10,
                columns: [{
                        data: 'nomor',
                        name: 'nomor',
                        className: 'text-center'
                    },
                    {
                        data: 'proyek',
                        name: 'proyek',
                        className: 'text-center'
                    },
                    {
                        data: 'periode',
                        name: 'periode',
                        className: 'text-center'
                    },
                    {
                        data: 'status',
                        name: 'status',
                        className: 'text-center',
                        render: function(data, type, row) {
                            if (row.status === 'Pengajuan') {
                                return `<span class="badge bg-primary">${row.status}</span>`;
                            } else if (row.status === 'Evaluasi') {
                                return `<span class="badge bg-warning">${row.status}</span>`;
                            } else if (row.status === 'Disetujui') {
                                return `<span class="badge bg-success">${row.status}</span>`;
                            } else {
                                return `<span class="badge bg-secondary">${row.status}</span>`;
                            }
                        }
                    },
                    {
                        data: 'evaluasi',
                        name: 'evaluasi',
                        className: 'text-center',
                        render: function(data, type, row) {
                            // Button will be disabled if the status ''
                            const disabled = row.status === 'Pengajuan' ? 'disabled' : '';
                            const icon = row.status === 'Evaluasi' ? 'fa-stamp' : 'fa-eye';
                            return `
        <button class="btn btn-primary mx-1 detailBtn" ${disabled} data-id="${row.id}" onclick="redirectToEvaluation(${row.id})">
            <i class="fa-solid ${icon}"></i>
        </button>
    `;
                        }
                    }
                ]
            }).on('page', function() {
                const currentPage = $('#table-data').DataTable().page();
                localStorage.setItem(lastPageKey, currentPage);
            });
        });


        function redirectToEvaluation(id) {
            const detailUrl = "{{ route('evaluasi_rkb_general.detail.index', ':id') }}".replace(':id', id);
            window.location.href = detailUrl;
        }
    </script>
@endpush
