<div class="ibox-body ms-0 ps-0 table-responsive">
    <table class="m-0 table table-bordered table-striped" id="table-data">
        <thead class="table-primary">
            <tr>
                <th class="text-center">Nama</th>
                <th class="text-center">Part Number</th>
                <th class="text-center">Merk</th>
                <th class="text-center">Detail</th>
                <th class="text-center">Aksi</th>
            </tr>
        </thead>
        <tbody>
            {{-- Content generated by DataTable --}}
        </tbody>
    </table>
</div>

@push('styles_3')
    <style>
    </style>
@endpush

@push('scripts_3')
    <script>
        $('#table-data').DataTable({
            processing: true,
            responsive: true,
            serverSide: true,
            ajax: {
                url: "{{ route('master-data.sparepart.getData') }}",
                type: "GET"
            },
            language: {
                paginate: {
                    previous: '<i class="bi bi-caret-left"></i>',
                    next: '<i class="bi bi-caret-right"></i>'
                }
            },
            pageLength: 10,
            lengthMenu: [
                [10, 25, 50],
                [10, 25, 50]
            ],
            ordering: true,
            order: [],
            columnDefs: [{
                    targets: 3, // Index of "Detail" column
                    className: 'text-center nowrap-column',
                    orderable: false,
                    searchable: false,
                    width: "1%",
                    render: function(data, type, row) {
                        return `
                    <button class="btn btn-info detailBtn" data-id="${row.id}" onclick="showDetailModal(${row.id})">
                        <i class="bi bi-eye"></i> Detail
                    </button>
                `;
                    }
                },
                {
                    targets: 4, // Index of "Aksi" column
                    className: 'text-center nowrap-column',
                    orderable: false,
                    searchable: false,
                    width: "1%",
                    render: function(data, type, row) {
                        return `
                    <button class="btn btn-danger deleteBtn" data-id="${row.id}">
                        <i class="bi bi-trash"></i>
                    </button>
                    <button class="btn btn-warning ms-3 ubahBtn" data-id="${row.id}" onclick="fillFormEdit(${row.id})">
                        <i class="bi bi-pencil-square"></i>
                    </button>
                `;
                    }
                }
            ],
            columns: [{
                    data: 'nama',
                    name: 'nama'
                },
                {
                    data: 'part_number',
                    name: 'part_number'
                },
                {
                    data: 'merk',
                    name: 'merk'
                },
                {
                    data: 'detail',
                    name: 'detail'
                }, // "Detail" column with button
                {
                    data: 'aksi',
                    name: 'aksi'
                } // "Aksi" column
            ]
        });
    </script>
@endpush
