@push('styles_3')
    <style>
        #table-data {
            font-size: 0.9em;
            white-space: nowrap;
        }

        #table-data td,
        #table-data th {
            padding: 4px 8px;
            vertical-align: middle;
        }
    </style>
@endpush

<div class="ibox-body ms-0 ps-0 table-responsive">
    <table class="m-0 table table-bordered table-striped" id="table-data">
        <thead class="table-primary">
            <tr>
                <th class="text-center">Nama Alat</th>
                <th class="text-center">Kategori Sparepart</th>
                <th class="text-center">Sparepart</th>
                <th class="text-center">Quantity</th>
                <th class="text-center">Satuan</th>
                <th class="text-center">Aksi</th>
            </tr>
        </thead>
        <tbody>
            {{-- Content generated by DataTable --}}
        </tbody>
    </table>
</div>

@push('scripts_3')
    <script>
        $(document).ready(function() {
            const lastPageKey = 'lastPage_detail_rkb';

            var lastPage = localStorage.getItem(lastPageKey) ? parseInt(localStorage.getItem(lastPageKey)) : 0;

            var table = $('#table-data').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                ajax: {
                    url: "{{ route('detail_rkb_general.getData', $rkb->id) }}",
                    type: "GET"
                },
                language: {
                    paginate: {
                        previous: '<i class="bi bi-caret-left"></i>',
                        next: '<i class="bi bi-caret-right"></i>'
                    }
                },
                pageLength: 10,
                lengthMenu: [
                    [10, 25, 50],
                    [10, 25, 50]
                ],
                ordering: true,
                order: [],
                displayStart: lastPage * 10,
                columnDefs: [{
                    targets: 5, // Target column for actions
                    className: 'text-center nowrap-column',
                    orderable: false,
                    searchable: false,
                    width: "1%",
                    render: function(data, type, row) {
                        // Check if is_finalized is true
                        const disabled = row.is_finalized ? 'disabled' : '';
                        return `
                        <button class="btn btn-warning mx-1 ubahBtn" ${disabled} onclick="fillFormEditDetailRKB(${row.id})" data-id="${row.id}">
                            <i class="bi bi-pencil-square"></i>
                        </button>
                        <button class="btn btn-danger mx-1 deleteBtn" ${disabled} data-id="${row.id}">
                            <i class="bi bi-trash"></i>
                        </button>
                    `;
                    }
                }],
                columns: [{
                        data: 'masterDataAlat',
                        name: 'masterDataAlat',
                        className: 'text-center'
                    },
                    {
                        data: 'kategoriSparepart',
                        name: 'kategoriSparepart',
                        className: 'text-center'
                    },
                    {
                        data: 'masterDataSparepart',
                        name: 'masterDataSparepart',
                        className: 'text-center'
                    },
                    {
                        data: 'quantity_requested',
                        name: 'quantity_requested',
                        className: 'text-center'
                    },
                    {
                        data: 'satuan',
                        name: 'satuan',
                        className: 'text-center'
                    },
                    {
                        data: 'aksi',
                        name: 'aksi',
                        className: 'text-center'
                    }
                ]
            });

            table.on('page', function() {
                var currentPage = table.page();
                localStorage.setItem(lastPageKey, currentPage);
            });
        });
    </script>
@endpush
