@push('styles_3')
    <style>
        #table-data {
            font-size: 0.9em;
            white-space: nowrap;
        }

        #table-data td,
        #table-data th {
            padding: 4px 8px;
            vertical-align: middle;
        }
    </style>
@endpush

<div class="ibox-body ms-0 ps-0 table-responsive">
    <table class="m-0 table table-bordered table-striped" id="table-data">
        <thead class="table-primary">
            <tr>
                <th class="text-center">No RKB</th>
                <th class="text-center">Proyek</th>
                <th class="text-center">Periode</th>
                <th class="text-center">Status</th>
                <th class="text-center">Ubah Detail</th>
                <th class="text-center">Aksi</th>
            </tr>
        </thead>
        <tbody>
            {{-- Content generated by DataTable --}}
        </tbody>
    </table>
</div>

@push('scripts_3')
    <script>
        $(document).ready(function() {
            var table = $('#table-data').DataTable({
                // pageLength: 0,
                paginate: false,
                // lengthMenu: [
                //     [100],
                //     [100]
                // ],
            });
        });
    </script>
@endpush
