@push('styles_3')
    <style>
        #table-data {
            font-size: 0.9em;
            white-space: nowrap;
        }

        #table-data td,
        #table-data th {
            /* padding: 4px 8px; */
            vertical-align: middle;
        }
    </style>
@endpush

<div class="ibox-body ms-0 ps-0 table-responsive">
    <table class="m-0 table table-bordered table-striped" id="table-data">
        <thead class="table-primary">
            <tr>
                <th class="text-center">Jenis Alat</th>
                <th class="text-center">Kode Alat</th>
                <th class="text-center">Merek Alat</th>
                <th class="text-center">Tipe Alat</th>
                <th class="text-center">Serial Number</th>
                <th class="text-center">Aksi</th>
            </tr>
        </thead>
        <tbody>
            {{-- Content generated by DataTable --}}
        </tbody>
    </table>
</div>

@push('scripts_3')
    <script>
        $(document).ready(function() {
            // Unique key for localStorage specific to this page
            const lastPageKey = 'lastPage_alat';

            // Retrieve the last page number from localStorage, if available
            var lastPage = localStorage.getItem(lastPageKey) ? parseInt(localStorage.getItem(lastPageKey)) : 0;

            var table = $('#table-data').DataTable({
                processing: true,
                responsive: true,
                serverSide: true,
                ajax: {
                    url: "{{ route('master-data.alat.getData') }}",
                    type: "GET"
                },
                language: {
                    paginate: {
                        previous: '<i class="bi bi-caret-left"></i>',
                        next: '<i class="bi bi-caret-right"></i>'
                    }
                },
                pageLength: 10,
                lengthMenu: [
                    [10, 25, 50],
                    [10, 25, 50]
                ],
                ordering: true,
                order: [],
                displayStart: lastPage * 10, // Mulai dari halaman terakhir yang disimpan
                columnDefs: [{
                    targets: 5, // Indeks kolom 'Aksi'
                    className: 'text-center nowrap-column',
                    orderable: false,
                    searchable: false,
                    width: "1%",
                    render: function(data, type, row) {
                        return `
<button class="btn btn-danger mx-1 deleteBtn" data-id="${row.id}">
<i class="bi bi-trash"></i>
</button>
`;
                    }
                }],
                columns: [{
                        data: 'jenis_alat',
                        name: 'jenis_alat'
                    },
                    {
                        data: 'kode_alat',
                        name: 'kode_alat'
                    },
                    {
                        data: 'merek_alat',
                        name: 'merek_alat'
                    },
                    {
                        data: 'tipe_alat',
                        name: 'tipe_alat'
                    },
                    {
                        data: 'serial_number',
                        name: 'serial_number'
                    },
                    {
                        data: 'aksi',
                        name: 'aksi'
                    }
                ]
            });

            // Save the current page number to localStorage each time the page changes
            table.on('page', function() {
                var currentPage = table.page();
                localStorage.setItem(lastPageKey, currentPage);
            });

            // Clear lastPage for this specific page key after table initialization
            // table.on('init', function() {
            //     localStorage.removeItem(lastPageKey);
            // });
        });
    </script>
@endpush
