@push('styles_3')
    <style>
        #table-data {
            font-size: 0.9em;
            white-space: nowrap;
        }

        #table-data td,
        #table-data th {
            /* padding: 4px 8px; */
            vertical-align: middle;
        }
    </style>
@endpush

<div class="ibox-body ms-0 ps-0 table-responsive">
    <table class="m-0 table table-bordered table-striped" id="table-data">
        <thead class="table-primary">
            <tr>
                <th class="text-center">No RKB</th>
                <th class="text-center">Proyek</th>
                <th class="text-center">Periode</th>
                <th class="text-center">Status</th>
                <th class="text-center">Ubah Detail</th>
                <th class="text-center">Aksi</th>
            </tr>
        </thead>
        <tbody>
            {{-- Content generated by DataTable --}}
        </tbody>
    </table>
</div>

@push('scripts_3')
    <script>
        $(document).ready(function() {
            // Unique key for localStorage specific to this page
            const lastPageKey = 'lastPage_rkb';

            // Retrieve the last page number from localStorage, if available
            var lastPage = localStorage.getItem(lastPageKey) ? parseInt(localStorage.getItem(lastPageKey)) : 0;

            var table = $('#table-data').DataTable({
                processing: true,
                responsive: true,
                serverSide: true,
                ajax: {
                    url: "{{ route('rkb_general.getData') }}",
                    type: "GET"
                },
                language: {
                    paginate: {
                        previous: '<i class="bi bi-caret-left"></i>',
                        next: '<i class="bi bi-caret-right"></i>'
                    }
                },
                pageLength: 10,
                lengthMenu: [
                    [10, 25, 50],
                    [10, 25, 50]
                ],
                ordering: true,
                order: [],
                displayStart: lastPage * 10, // Start from the last saved page
                columnDefs: [{
                        targets: 3, // Kolom "Status"
                        className: 'text-center',
                        orderable: false,
                        data: 'status', // Menggunakan data yang dikembalikan dari backend
                        render: function(data, type, row) {
                            if (row.status === "Pengajuan") {
                                return `<span class="badge bg-primary w-100">Pengajuan</span>`;
                            } else if (row.status === "Evaluasi") {
                                return `<span class="badge bg-warning w-100">Evaluasi</span>`;
                            } else if (row.status === "Disetujui") {
                                return `<span class="badge bg-success w-100">Disetujui</span>`;
                            } else {
                                return `<span class="badge bg-secondary w-100">Tidak Diketahui</span>`;
                            }
                        }
                    },
                    {
                        targets: 4, // Kolom "Aksi" untuk detail
                        className: 'text-center nowrap-column',
                        orderable: false,
                        searchable: false,
                        width: "1%",
                        render: function(data, type, row) {
                            return `
<button class="btn btn-info mx-1 detailBtn" data-id="${row.id}" onclick="redirectToDetail(${row.id})">
<i class="fa-solid fa-file-pen"></i>
</button>
`;
                        }
                    },
                    {
                        targets: 5, // Kolom "Aksi" untuk edit dan delete
                        className: 'text-center nowrap-column',
                        orderable: false,
                        searchable: false,
                        width: "1%",
                        render: function(data, type, row) {
                            const disabled = row.is_finalized ? 'disabled' : '';
                            return `
<button class="btn btn-warning mx-1 ubahBtn" ${disabled} data-id="${row.id}" onclick="fillFormEditRKB(${row.id})">
<i class="bi bi-pencil-square"></i>
</button>
<button class="btn btn-danger mx-1 deleteBtn" ${disabled} data-id="${row.id}">
<i class="bi bi-trash"></i>
</button>
`;
                        }
                    }
                ],
                columns: [{
                        data: 'nomor',
                        name: 'nomor',
                        className: 'text-center'
                    },
                    {
                        data: 'proyek',
                        name: 'proyek',
                        className: 'text-center'
                    },
                    {
                        data: 'periode',
                        name: 'periode',
                        className: 'text-center'
                    },
                    {
                        data: null,
                        name: 'status',
                        className: 'text-center',
                    },
                    {
                        data: null,
                        name: 'aksi',
                        className: 'text-center',
                    },
                    {
                        data: null,
                        name: 'aksi',
                        className: 'text-center',
                    }
                ]
            });

            // Save the current page number to localStorage each time the page changes
            table.on('page', function() {
                var currentPage = table.page();
                localStorage.setItem(lastPageKey, currentPage);
            });
        });

        // Function to redirect to detail page
        function redirectToDetail(id) {
            const detailUrl = "{{ route('rkb_general.detail.index', ':id') }}".replace(':id', id);
            window.location.href = detailUrl;
        }
    </script>
@endpush
